Repository projectcontour/contour-operator, pull requests merged in 2021-08, with the labels that each got.

#421 Add GatewayControllerName field to Contour CRD
  api/v1alpha1/contour_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.projectcontour.io_contours.yaml
  examples/operator/operator.yaml
Labels: release-note

#422 Drop GatewayClass/Gateway controllers
  api/v1alpha1/contour_types.go
  api/v1alpha1/helpers.go
  config/crd/bases/operator.projectcontour.io_contours.yaml
  examples/gateway/gateway.yaml
  examples/operator/operator.yaml
  internal/controller/controller.go
  internal/controller/gateway/controller.go
  internal/controller/gatewayclass/controller.go
  internal/objects/configmap/configmap.go
  internal/objects/configmap/configmap_test.go
  internal/objects/contour/contour.go
  internal/objects/deployment/deployment.go
  internal/objects/gateway/finalizer.go
  internal/objects/gateway/gateway.go
  internal/objects/gatewayclass/finalizer.go
  internal/objects/gatewayclass/gatewayclass.go
  internal/operator/operator.go
  internal/operator/operator_test.go
  pkg/validation/validation.go
  pkg/validation/validation_test.go
  test/e2e/operator_test.go
  test/e2e/utils.go
Labels: release-note, release-note-action-required

#427 Remove strange number `|2` in configmap
  internal/objects/configmap/configmap.go
  internal/objects/configmap/configmap_test.go
Labels: kind/bug

#428 updates for Kubernetes 1.22
  .github/workflows/prbuild.yaml
  go.mod
  go.sum
  hack/actions/install-kubernetes-toolchain.sh
Labels: release-note
